- hosts: all
  become : true
  tasks:
    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: "Add nodejs 12.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x buster main
        update_cache: yes
    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present
    - name: "Install yarn"
      npm:
        name: yarn
        global: yes
